name: Deploy to server agel 🚀

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Ensure Storage and Cache Paths Exist
      run: |
        mkdir -p storage/framework/cache
        mkdir -p storage/framework/sessions
        mkdir -p storage/framework/views
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Prevent SSH Timeout
      run: |
        mkdir -p ~/.ssh
        echo "ServerAliveInterval 60" >> ~/.ssh/config


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        TARGET: domains/topbusiness.ebharbook.com/public_html/agel
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: 194.163.35.142
        REMOTE_USER: u369694554
        REMOTE_PORT: 65002
        ARGS: "-avz --partial --append"
        EXCLUDE: |
          .git
          .github
          .env.example
          npm-debug.log
    
    - name: Run Server Commands
      uses: appleboy/ssh-action@master
      with:
        host: 194.163.35.142
        username: u369694554
        port: 65002
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd domains/topbusiness.ebharbook.com/public_html/agel
          php artisan optimize:clear
          php artisan migrate --seed
